# Generated by Django 5.2.13 on 2026-04-28 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rewear", "0003_item_current_holder_swap_address_submitted_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="read_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="swap",
            name="delivered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="swap",
            name="fulfillment_status",
            field=models.CharField(
                choices=[
                    ("awaiting_address", "Awaiting Address"),
                    ("ready_to_ship", "Ready to Ship"),
                    ("shipped", "Shipped"),
                    ("delivered", "Delivered"),
                ],
                default="awaiting_address",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="swap",
            name="shipped_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
